### ISSUE TITLE
miwuploader.apk does not work for the smart band 7 pro

### ISSUE THREAD

**Issue by vonfritz** [Mino260806/mi-watchface-uploader#2]
Hi, tried sseveral times but mi-fitness downloads the selected watchface and does not apply rhe copied one.
mi fitness version 3.9.1i
magisk version 25.2
LSPosed version 1.8.5
tryed with the Zygisk version
LSPoswd and Mi  watch face uploader are active.

**Comment by Mino260806** [comment]
I forgot to say that you must rename the watchface to exactly `custom_watchface`😅
Please confirm that it works

**Comment by vonfritz** [comment]
I state that I have a 7 pro and not in redmi.
Renaming the watch face to custom_watchface seems to load it correctly, but it is not displayed in the watch but only in the "local" folder of the application after manually synchronizing.
If I recall the watch face from the local folder and apply it everything is displayed distorted. Another thing the dials loaded in that way are no longer erasable. pressing delete they are not deleted and remain in the local folder.
so for the 7 pro it's not good.

**Comment by vonfritz** [comment]
After reboot the watch it is possible to delete the "broken" watch faces from the local section of the mi fitness application.

**Comment by Domenick90** [comment]
> If I recall the watch face from the local folder and apply it everything is displayed distorted

What does is displayed distorted (attach photo) ? Can you try a different dial?

**Comment by vonfritz** [comment]
it practically doesn't replace the old watch face But it partially overwrites it.

**Comment by Domenick90** [comment]
ROOT Method works well in Redmi Watch 2!

**Comment by vonfritz** [comment]
> ROOT Method works well in Redmi Watch 2!

Well, I tried to load a redmi 2 watch face but it didn't work anyway. 😁

**Comment by Domenick90** [comment]
> Well, I tried to load a redmi 2 watch face but it didn't work anyway. 😁
Xm, strange. The method worked for a user from the 4pda forum

**Comment by vonfritz** [comment]
> > Well, I tried to load a redmi 2 watch face but it didn't work anyway. 😁
> Xm, strange. The method worked for a user from the 4pda forum
> 

It was a joke I loaded it on la7 Pro. 😜

**Comment by Domenick90** [comment]
So you need a fix for Mi band 7pro :-)

**Comment by vonfritz** [comment]
![IMG_20221204_140827.jpg](https://user-images.githubusercontent.com/2198615/205492339-3a320655-6750-4adc-a924-442abe82b07c.jpg redmi 2 watch face on 7 Pro watch.  must be reset to remove the watch face after. 😂

**Comment by Domenick90** [comment]
> ![IMG_20221204_140827.jpg](https://user-images.githubusercontent.com/2198615/205492339-3a320655-6750-4adc-a924-442abe82b07c.jpg redmi 2 watch face on 7 Pro watch. must be reset to remove the watch face after. 😂

They are incompatible ;-P

**Comment by vonfritz** [comment]
> fix

Yeah the thread issue is about the  7 Pro not for the redmi 2. 😉

**Comment by dudumaroja** [comment]
i have a band 7 pro.. i willing to do testings.. root and non root... but i need some custom watch faces.. of some guide on how to modify default ones to test.

**Comment by vonfritz** [comment]
> i have a band 7 pro.. i willing to do testings.. root and non root... but i need some custom watch faces.. of some guide on how to modify default ones to test.

there is currently nothing to test here as it doesn't work for the 7 Pro you have to wait for the author to have time to post a working version. As for how to edit the watch faces you have to unpack, edit and then repack. To do this, there are currently some Russian tools and mods that are not publicly available. but @Domenick90  can explain this to you better. ;)

**Comment by Domenick90** [comment]
> i have a band 7 pro.. i willing to do testings.. root and non root... but i need some custom watch faces.. of some guide on how to modify default ones to test.

Hello! Join the group in TG https://t.me/mi_watch_int - there are tools to work with MB7Pro watchfaces.

**Comment by vonfritz** [comment]
@Domenick90 Have you tried to use this uploader with the redmi watch 3 ? I don't want to risk to destroy mjne. :)

**Comment by Domenick90** [comment]
> @Domenick90 Have you tried to use this uploader with the redmi watch 3 ? I don't want to risk to destroy mjne. :)

I don't have a Redmi Watch 3. I think nothing bad will happen, in a pinch you can remove the module

**Comment by Domenick90** [comment]
> @Domenick90 Have you tried to use this uploader with the redmi watch 3 ? I don't want to risk to destroy mjne. :)

@vonfritz Im tested on redmi watch 3 china. Root method working well!

**Comment by vonfritz** [comment]
I don't think there will ever be any updates here. Now it is possible to use Notify for Xiaomi to load watch faces from the internal folder. Close this.
